"""Export service — generate PDF and DOCX reports of approved standards mappings."""

import io
import datetime


def generate_pdf_report(tender_title: str, mappings: list[dict]) -> bytes:
    """
    Generate a PDF report mapping requirements to approved standards.

    Args:
        tender_title: Title of the tender
        mappings: List of dicts with keys: requirement, standards (list of {is_number, title, justification})

    Returns:
        PDF file bytes
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['Heading1'], fontSize=16, spaceAfter=20,
        textColor=colors.HexColor("#1a365d"),
    )
    elements.append(Paragraph("Manak Mitra — Standards Recommendation Report", title_style))
    elements.append(Spacer(1, 10))

    # Tender info
    elements.append(Paragraph(f"<b>Tender:</b> {tender_title}", styles["Normal"]))
    elements.append(Paragraph(
        f"<b>Generated:</b> {datetime.datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        styles["Normal"],
    ))
    elements.append(Spacer(1, 20))

    # Summary
    total_reqs = len(mappings)
    total_standards = sum(len(m.get("standards", [])) for m in mappings)
    elements.append(Paragraph(
        f"<b>Summary:</b> {total_reqs} requirements mapped to {total_standards} approved Indian Standards.",
        styles["Normal"],
    ))
    elements.append(Spacer(1, 20))

    # Mappings table
    for i, mapping in enumerate(mappings, 1):
        # Requirement header
        req_style = ParagraphStyle(
            f'ReqHeader_{i}', parent=styles['Heading3'], fontSize=11,
            textColor=colors.HexColor("#2d3748"), spaceAfter=8,
        )
        elements.append(Paragraph(
            f"Requirement {i}: [{mapping.get('req_type', 'Technical').upper()}] {mapping['requirement'][:200]}",
            req_style,
        ))

        standards = mapping.get("standards", [])
        if standards:
            table_data = [["IS Number", "Title", "Justification"]]
            for std in standards:
                table_data.append([
                    std["is_number"],
                    Paragraph(std["title"], styles["Normal"]),
                    Paragraph(std.get("justification", "")[:200], styles["Normal"]),
                ])

            col_widths = [1.2 * inch, 2.5 * inch, 3.0 * inch]
            table = Table(table_data, colWidths=col_widths, repeatRows=1)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2d3748")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),
            ]))
            elements.append(table)
        else:
            elements.append(Paragraph("<i>No approved standards for this requirement.</i>", styles["Normal"]))

        elements.append(Spacer(1, 15))

    # Footer
    elements.append(Spacer(1, 30))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
    elements.append(Paragraph(
        "This report was generated by Manak Mitra — AI-powered Indian Standards Recommender. "
        "Recommendations should be verified by a domain expert before inclusion in final tender documents.",
        footer_style,
    ))

    doc.build(elements)
    return buffer.getvalue()


def generate_docx_report(tender_title: str, mappings: list[dict]) -> bytes:
    """
    Generate a DOCX report mapping requirements to approved standards.

    Returns:
        DOCX file bytes
    """
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    title = doc.add_heading("Manak Mitra — Standards Recommendation Report", level=1)
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x1a, 0x36, 0x5d)

    doc.add_paragraph(f"Tender: {tender_title}")
    doc.add_paragraph(f"Generated: {datetime.datetime.now().strftime('%d %B %Y, %I:%M %p')}")

    total_reqs = len(mappings)
    total_standards = sum(len(m.get("standards", [])) for m in mappings)
    doc.add_paragraph(f"Summary: {total_reqs} requirements mapped to {total_standards} approved Indian Standards.")
    doc.add_paragraph("")

    for i, mapping in enumerate(mappings, 1):
        doc.add_heading(
            f"Requirement {i}: [{mapping.get('req_type', 'Technical').upper()}]",
            level=2,
        )
        doc.add_paragraph(mapping["requirement"][:500])

        standards = mapping.get("standards", [])
        if standards:
            table = doc.add_table(rows=1, cols=3)
            table.style = "Light Grid Accent 1"
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = "IS Number"
            hdr_cells[1].text = "Title"
            hdr_cells[2].text = "Justification"

            for std in standards:
                row_cells = table.add_row().cells
                row_cells[0].text = std["is_number"]
                row_cells[1].text = std["title"]
                row_cells[2].text = std.get("justification", "")[:200]
        else:
            doc.add_paragraph("No approved standards for this requirement.", style="List Bullet")

        doc.add_paragraph("")

    # Footer
    footer_para = doc.add_paragraph(
        "This report was generated by Manak Mitra — AI-powered Indian Standards Recommender. "
        "Recommendations should be verified by a domain expert before inclusion in final tender documents."
    )
    for run in footer_para.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
